apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
data:
  RABBIT_HOST: "{{ .Values.rabbit.host }}"
  RABBIT_TIMEOUT: "{{ .Values.rabbit.timeout }}"
  RABBIT_QUEUE_NAME: "{{ .Values.rabbit.queue }}"
  MONGO_HOST: "{{ .Values.mongo.host }}"
  MONGO_PORT: "{{ .Values.mongo.port }}"
  DATABASE_NAME: "{{ .Values.mongo.database }}"
