
appName: ms-autorizador
replicaCount: 2
labelType: backend

rabbit:
  host: rabbitmq.backend.svc
  timeout: 30000
  queue: compras-queue

mongo:
  host: mongo.backend.svc
  port: 27017
  database: compras

container:
  repo: jonathasgarcia
  name: ms-autorizador
  port: 8090
  nodePort: 30082
  type: NodePort

host:
  path: /ms-autorizador



